### ISSUE TITLE
Potential issue with the decompression

### ISSUE THREAD

**Issue by mzdravkov** [bsaintjo/pod5-rs#1]
Hello @bsaintjo,

Thank you very much for working on this project! I found the repo some few weeks ago and it seemed inactive so I tried to pick up the work from where it was at the time. I wanted to get something working and maybe open a pull request with it. I don't know Rust at all (I'm using this project as a vehicle for learning it) so I've been making quite a slow progress.

I just managed to start reading the signal data and was observing that it seems that I'm getting different results than the ONT's pod5 Python library. And seeing that you've started working on the project again, I thought it might be a good idea to report it. It's quite possible that there's no problem at all and it's just my ignorance, so apologies if that's the case.

## Steps to reproduce:

I tried to look at the raw compressed signal data for the first read in file `extra/multi_fast5_zip_v3.pod5` (that is read `0000173c-bf67-44e7-9a9c-1ad0bc728e74`).

I used my implementation to get the compressed signal and compared the first few bytes to ones I retrieve with ONT's Python library in the following manner:

```python
import pod5
import numpy as np

reader =  pod5.Reader("extra/multi_fast5_zip_v3.pod5")
read = next(reader.reads())
batch, batch_index, row_index = read._find_signal_row_index(0)
read_compressed_signal  = batch.signal[row_index].as_py()  # get the signal row as bytes
signal_row_samples = batch.samples[row_index].as_py() # get the number of samples in the signal row
compressed_signal_array = np.array(list(read_compressed_signal))
# The bytes in compressed_signal_array are the same as the ones I get for the compressed signal from my rust implementation
decompressed_signal = pod5.vbz_decompress_signal(compressed_signal_array, signal_row_samples)
# The bytes in decompressed_signal are different than the ones I get from using your implementation of svb16.
```

And the way I decompress the signal in Rust:
```rust
let mut decoded = decode(compressed_signal, samples).unwrap();
```
where both `compressed_signal` and `samples` have the same values as the ones passed to the Python decompression function, but the result from the decompression is different.

PS: You can use the python snippet and compare the `decompressed_signal` bytes from it with the test function in `reader.rs`.

**Comment by btpsj** [comment]
Thanks, @mzdravkov, for the detailed notes! It will help make things easier to figure out the issue.

Just to confirm, when you call in your Rust code:
```rust
let mut decoded = decode(compressed_signal, samples).unwrap();
```
Do you ever get a panic from the `.unwrap()` call, or does it always work fine, and are the bytes just incorrect?

**Comment by mzdravkov** [comment]
Only the bytes are incorrect.
I tried to run the decoding for all reads in `extra/multi_fast5_zip_v3.pod5 ` and I didn't get any panic.

**Comment by btpsj** [comment]
Commit 922e2ba should have fixed it. The issue was caused by interpreting the control bits in the wrong order, and it should have been the least significant bit first.

Thanks for your code and for submitting this issue. The example code helped put together an example to debug the problem. Let me know if this most recent update resolves your problem.

**Comment by mzdravkov** [comment]
I just tested again with the latest version and the issue is resolved. Thanks a lot!
